### ISSUE TITLE
Update project url

### ISSUE THREAD

**Issue by timhoffm** [swfiua/blume#1]
https://github.com/swfiua/blume/blob/5dc962851f7ae4d76c45cc5bf4736cc10e0e432a/setup.py#L25

should be replaced by https://github.com/swfiua/blume

This leads to PyPI homepage link currently being broken:

![image](https://user-images.githubusercontent.com/2836374/79082311-02a74500-7d25-11ea-9d71-57bdfa7427b2.png)

**Comment by swfiua** [comment]
Thanks.

Sorry to be slow on this.

I noticed it the other day when copying the setup.py to another project.
