### ISSUE TITLE
"KeyError: Text" when trying an example

### ISSUE THREAD

**Issue by Denubis** [swfiua/blume#4]
Python 3.9.5, ubuntu, running in a pyenv. (Reproduced outside of my larger project)

```
$ pip install blume
$ python3 multiline.py

brian@Baudrillard:~/people/ray/blume$ python3 multiline.py 
Traceback (most recent call last):
  File "/home/brian/people/ray/blume/multiline.py", line 8, in <module>
    from blume.table import table
  File "/home/brian/people/ray/blume/.direnv/python-3.9.5/lib/python3.9/site-packages/blume/table.py", line 31, in <module>
    class Cell(Rectangle):
  File "/home/brian/people/ray/blume/.direnv/python-3.9.5/lib/python3.9/site-packages/blume/table.py", line 261, in Cell
    def set_text_props(self, **kwargs):
  File "/home/brian/people/ray/blume/.direnv/python-3.9.5/lib/python3.9/site-packages/matplotlib/docstring.py", line 40, in __call__
    func.__doc__ = inspect.cleandoc(func.__doc__) % self.params
KeyError: 'Text'
```
I... suspect it's me that has the error, but I can't figure out what could be causing it from a clean venv.

**Comment by swfiua** [comment]
I need to do another release.

Something changed in the matplotlib docstring magic and it is getting confused whilst trying to be helpful ;)

The version on github should be ok -- it looks like I started fixing this a couple of days ago.

**Comment by Denubis** [comment]
I can confirm that `pip install --force-reinstall --upgrade git+https://github.com/swfiua/blume.git` worked.

**Comment by swfiua** [comment]
Thanks + thanks for the report too.
I just pushed out another little fix to the offending docstring.

**Comment by Denubis** [comment]
Let me know when there's a release and I'll test that, too :)

**Comment by swfiua** [comment]
Thanks -- I'm on a bit of a legend diversion at the moment + there's some general bit rot I should deal with.  

I'll add a note here when the release goes out

**Comment by swfiua** [comment]
I just put out version 0.2 with this fix.

Sorry about the delay, I was hoping to put out a new version of the table using the same code as the legend, but it is proving a little trickier than I was hoping ;)

Thanks again for the report.
